//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dataEntities : DbContext
    {
        public dataEntities()
            : base("name=dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cluster> clusters { get; set; }
        public virtual DbSet<activitylog> activitylogs { get; set; }
        public virtual DbSet<applicense> applicenses { get; set; }
        public virtual DbSet<block> blocks { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<classlevel> classlevels { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<subjectclassmapping> subjectclassmappings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<teacherclassmapping> teacherclassmappings { get; set; }
        public virtual DbSet<teachersubjectmapping> teachersubjectmappings { get; set; }
        public virtual DbSet<textbook> textbooks { get; set; }
        public virtual DbSet<type> types { get; set; }
        public virtual DbSet<userrole> userroles { get; set; }
        public virtual DbSet<videodata> videodatas { get; set; }
        public virtual DbSet<listmaster> listmasters { get; set; }
        public virtual DbSet<listtype> listtypes { get; set; }
        public virtual DbSet<smslog> smslogs { get; set; }
        public virtual DbSet<smstemplate> smstemplates { get; set; }
        public virtual DbSet<transactionlog> transactionlogs { get; set; }
    
        public virtual ObjectResult<Get_User_Login_Result> Get_User_Login(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_Login_Result>("Get_User_Login", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateUserPassword(Nullable<int> user_Id, string current_Password, string new_Password)
        {
            var user_IdParameter = user_Id.HasValue ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(int));
    
            var current_PasswordParameter = current_Password != null ?
                new ObjectParameter("Current_Password", current_Password) :
                new ObjectParameter("Current_Password", typeof(string));
    
            var new_PasswordParameter = new_Password != null ?
                new ObjectParameter("New_Password", new_Password) :
                new ObjectParameter("New_Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateUserPassword", user_IdParameter, current_PasswordParameter, new_PasswordParameter);
        }
    
        public virtual ObjectResult<Get_State_List_Result> Get_State_List(Nullable<int> country_Id)
        {
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_State_List_Result>("Get_State_List", country_IdParameter);
        }
    
        public virtual ObjectResult<Get_City_List_Result> Get_City_List(Nullable<int> country_Id, Nullable<int> state_Id)
        {
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var state_IdParameter = state_Id.HasValue ?
                new ObjectParameter("State_Id", state_Id) :
                new ObjectParameter("State_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_City_List_Result>("Get_City_List", country_IdParameter, state_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> City_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("City_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Nullable<int>> State_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("State_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Nullable<int>> Upload_video_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Upload_video_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Nullable<int>> Teacher_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Teacher_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Get_School_List_Result> Get_School_List(string sSearch, Nullable<int> user_Id, Nullable<int> startIndex, Nullable<int> maximumRows, ObjectParameter totalRecords)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            var user_IdParameter = user_Id.HasValue ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(int));
    
            var startIndexParameter = startIndex.HasValue ?
                new ObjectParameter("StartIndex", startIndex) :
                new ObjectParameter("StartIndex", typeof(int));
    
            var maximumRowsParameter = maximumRows.HasValue ?
                new ObjectParameter("MaximumRows", maximumRows) :
                new ObjectParameter("MaximumRows", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_School_List_Result>("Get_School_List", sSearchParameter, user_IdParameter, startIndexParameter, maximumRowsParameter, totalRecords);
        }
    
        public virtual ObjectResult<Get_Teacher_List_Result> Get_Teacher_List(string sSearch, Nullable<int> user_Id, Nullable<int> startIndex, Nullable<int> maximumRows, ObjectParameter totalRecords)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            var user_IdParameter = user_Id.HasValue ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(int));
    
            var startIndexParameter = startIndex.HasValue ?
                new ObjectParameter("StartIndex", startIndex) :
                new ObjectParameter("StartIndex", typeof(int));
    
            var maximumRowsParameter = maximumRows.HasValue ?
                new ObjectParameter("MaximumRows", maximumRows) :
                new ObjectParameter("MaximumRows", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Teacher_List_Result>("Get_Teacher_List", sSearchParameter, user_IdParameter, startIndexParameter, maximumRowsParameter, totalRecords);
        }
    
        public virtual ObjectResult<Get_TextBook_List_Result> Get_TextBook_List(string sSearch)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TextBook_List_Result>("Get_TextBook_List", sSearchParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Block_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Block_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Get_Block_List_Result> Get_Block_List(string sSearch)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Block_List_Result>("Get_Block_List", sSearchParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TextBook_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TextBook_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Nullable<int>> School_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("School_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Nullable<int>> Subject_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Subject_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Nullable<int>> Class_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Class_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Nullable<int>> Cluster_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Cluster_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Nullable<int>> Type_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Type_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Get_UploadVideo_List_Result> Get_UploadVideo_List(string sSearch, Nullable<int> startIndex, Nullable<int> maximumRows, ObjectParameter totalRecords)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            var startIndexParameter = startIndex.HasValue ?
                new ObjectParameter("StartIndex", startIndex) :
                new ObjectParameter("StartIndex", typeof(int));
    
            var maximumRowsParameter = maximumRows.HasValue ?
                new ObjectParameter("MaximumRows", maximumRows) :
                new ObjectParameter("MaximumRows", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_UploadVideo_List_Result>("Get_UploadVideo_List", sSearchParameter, startIndexParameter, maximumRowsParameter, totalRecords);
        }
    
        public virtual ObjectResult<Nullable<int>> country_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("country_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    
        public virtual ObjectResult<Get_Subject_List_Result> Get_Subject_List(string classids, string sSearch)
        {
            var classidsParameter = classids != null ?
                new ObjectParameter("classids", classids) :
                new ObjectParameter("classids", typeof(string));
    
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Subject_List_Result>("Get_Subject_List", classidsParameter, sSearchParameter);
        }
    
        public virtual ObjectResult<Get_teacher_class_Result> Get_teacher_class(Nullable<int> teacherid)
        {
            var teacheridParameter = teacherid.HasValue ?
                new ObjectParameter("teacherid", teacherid) :
                new ObjectParameter("teacherid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_teacher_class_Result>("Get_teacher_class", teacheridParameter);
        }
    
        public virtual ObjectResult<Get_teacher_subject_Result> Get_teacher_subject(Nullable<int> teacherid)
        {
            var teacheridParameter = teacherid.HasValue ?
                new ObjectParameter("teacherid", teacherid) :
                new ObjectParameter("teacherid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_teacher_subject_Result>("Get_teacher_subject", teacheridParameter);
        }
    
        public virtual ObjectResult<Get_Activitylogs_List_Result> Get_Activitylogs_List(string sSearch, Nullable<int> startIndex, Nullable<int> maximumRows, ObjectParameter totalRecords)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            var startIndexParameter = startIndex.HasValue ?
                new ObjectParameter("StartIndex", startIndex) :
                new ObjectParameter("StartIndex", typeof(int));
    
            var maximumRowsParameter = maximumRows.HasValue ?
                new ObjectParameter("MaximumRows", maximumRows) :
                new ObjectParameter("MaximumRows", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Activitylogs_List_Result>("Get_Activitylogs_List", sSearchParameter, startIndexParameter, maximumRowsParameter, totalRecords);
        }
    
        public virtual ObjectResult<Get_Teacher_Subject_List_Result> Get_Teacher_Subject_List(string classid)
        {
            var classidParameter = classid != null ?
                new ObjectParameter("classid", classid) :
                new ObjectParameter("classid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Teacher_Subject_List_Result>("Get_Teacher_Subject_List", classidParameter);
        }
    
        public virtual ObjectResult<Get_Dashboard_Chart_data_Result> Get_Dashboard_Chart_data(string chartType, string sSearch)
        {
            var chartTypeParameter = chartType != null ?
                new ObjectParameter("ChartType", chartType) :
                new ObjectParameter("ChartType", typeof(string));
    
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Dashboard_Chart_data_Result>("Get_Dashboard_Chart_data", chartTypeParameter, sSearchParameter);
        }
    
        public virtual ObjectResult<Get_Transactions_List_Result> Get_Transactions_List(string sSearch)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Transactions_List_Result>("Get_Transactions_List", sSearchParameter);
        }
    
        public virtual ObjectResult<Get_Country_List_Result> Get_Country_List(string sSearch)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Country_List_Result>("Get_Country_List", sSearchParameter);
        }
    
        public virtual ObjectResult<Get_classlevels_List_Result> Get_classlevels_List(string sSearch)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_classlevels_List_Result>("Get_classlevels_List", sSearchParameter);
        }
    
        public virtual ObjectResult<Get_clusters_List_Result> Get_clusters_List(string sSearch)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_clusters_List_Result>("Get_clusters_List", sSearchParameter);
        }
    
        public virtual ObjectResult<Get_types_List_Result> Get_types_List(string sSearch)
        {
            var sSearchParameter = sSearch != null ?
                new ObjectParameter("sSearch", sSearch) :
                new ObjectParameter("sSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_types_List_Result>("Get_types_List", sSearchParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> transactionlog_SaveUpdateDelete(string xmlString, Nullable<bool> isDelete, ObjectParameter outIdentity)
        {
            var xmlStringParameter = xmlString != null ?
                new ObjectParameter("XmlString", xmlString) :
                new ObjectParameter("XmlString", typeof(string));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("transactionlog_SaveUpdateDelete", xmlStringParameter, isDeleteParameter, outIdentity);
        }
    }
}
