//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class activitylog
    {
        public long activityid { get; set; }
        public System.DateTime activitydate { get; set; }
        public string application { get; set; }
        public string type { get; set; }
        public string details { get; set; }
        public int userid { get; set; }
        public string appversion { get; set; }
    }
}
