//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class smslog
    {
        public int smslogid { get; set; }
        public int smsid { get; set; }
        public long refid { get; set; }
        public int reftypeid { get; set; }
        public string smsmobileno { get; set; }
        public string smstemplate { get; set; }
        public int companyid { get; set; }
        public int branchid { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
    }
}
