//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class smstemplate
    {
        public int smsid { get; set; }
        public int listid { get; set; }
        public string smstemplate1 { get; set; }
        public int companyid { get; set; }
    }
}
