//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.cities = new HashSet<city>();
            this.schools = new HashSet<school>();
            this.teachers = new HashSet<teacher>();
        }
    
        public int stateid { get; set; }
        public string statename { get; set; }
        public int countryid { get; set; }
        public int createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public string remakrs { get; set; }
        public Nullable<bool> isactive { get; set; }
    
        public virtual ICollection<city> cities { get; set; }
        public virtual country country { get; set; }
        public virtual ICollection<school> schools { get; set; }
        public virtual ICollection<teacher> teachers { get; set; }
    }
}
