//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public teacher()
        {
            this.blocks = new HashSet<block>();
            this.blocks1 = new HashSet<block>();
            this.cities = new HashSet<city>();
            this.cities1 = new HashSet<city>();
            this.classlevels = new HashSet<classlevel>();
            this.classlevels1 = new HashSet<classlevel>();
            this.clusters = new HashSet<cluster>();
            this.clusters1 = new HashSet<cluster>();
            this.countries = new HashSet<country>();
            this.countries1 = new HashSet<country>();
            this.schools = new HashSet<school>();
            this.schools1 = new HashSet<school>();
            this.teacher1 = new HashSet<teacher>();
            this.teacher11 = new HashSet<teacher>();
            this.teacherclassmappings = new HashSet<teacherclassmapping>();
            this.teachersubjectmappings = new HashSet<teachersubjectmapping>();
            this.textbooks = new HashSet<textbook>();
            this.textbooks1 = new HashSet<textbook>();
            this.types = new HashSet<type>();
            this.types1 = new HashSet<type>();
            this.userroles = new HashSet<userrole>();
            this.userroles1 = new HashSet<userrole>();
            this.videodatas = new HashSet<videodata>();
            this.videodatas1 = new HashSet<videodata>();
        }
    
        public int teacherid { get; set; }
        public int blockid { get; set; }
        public string teacherfirstname { get; set; }
        public string teacherlastname { get; set; }
        public string teachermobile { get; set; }
        public string teacheremail { get; set; }
        public string teacheraddress { get; set; }
        public int countryid { get; set; }
        public int stateid { get; set; }
        public int cityid { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isblockadmin { get; set; }
        public string password { get; set; }
        public Nullable<int> userroleid { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> schoolid { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public string gmailid { get; set; }
        public string imgprofile { get; set; }
        public string otpcode { get; set; }
        public Nullable<System.DateTime> optexpiredon { get; set; }
    
        public virtual ICollection<block> blocks { get; set; }
        public virtual ICollection<block> blocks1 { get; set; }
        public virtual block block { get; set; }
        public virtual ICollection<city> cities { get; set; }
        public virtual ICollection<city> cities1 { get; set; }
        public virtual city city { get; set; }
        public virtual ICollection<classlevel> classlevels { get; set; }
        public virtual ICollection<classlevel> classlevels1 { get; set; }
        public virtual ICollection<cluster> clusters { get; set; }
        public virtual ICollection<cluster> clusters1 { get; set; }
        public virtual ICollection<country> countries { get; set; }
        public virtual ICollection<country> countries1 { get; set; }
        public virtual country country { get; set; }
        public virtual ICollection<school> schools { get; set; }
        public virtual ICollection<school> schools1 { get; set; }
        public virtual school school { get; set; }
        public virtual state state { get; set; }
        public virtual ICollection<teacher> teacher1 { get; set; }
        public virtual teacher teacher2 { get; set; }
        public virtual ICollection<teacher> teacher11 { get; set; }
        public virtual teacher teacher3 { get; set; }
        public virtual userrole userrole { get; set; }
        public virtual ICollection<teacherclassmapping> teacherclassmappings { get; set; }
        public virtual ICollection<teachersubjectmapping> teachersubjectmappings { get; set; }
        public virtual ICollection<textbook> textbooks { get; set; }
        public virtual ICollection<textbook> textbooks1 { get; set; }
        public virtual ICollection<type> types { get; set; }
        public virtual ICollection<type> types1 { get; set; }
        public virtual ICollection<userrole> userroles { get; set; }
        public virtual ICollection<userrole> userroles1 { get; set; }
        public virtual ICollection<videodata> videodatas { get; set; }
        public virtual ICollection<videodata> videodatas1 { get; set; }
    }
}
