//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class textbook
    {
        public textbook()
        {
            this.videodatas = new HashSet<videodata>();
        }
    
        public int textbookid { get; set; }
        public string textbookname { get; set; }
        public int subjectid { get; set; }
        public string remarks { get; set; }
        public bool isactive { get; set; }
        public int createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual teacher teacher { get; set; }
        public virtual teacher teacher1 { get; set; }
        public virtual ICollection<videodata> videodatas { get; set; }
    }
}
