//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class videodata
    {
        public int videoid { get; set; }
        public string videotitle { get; set; }
        public int teacherid { get; set; }
        public System.DateTime videodate { get; set; }
        public int classlevelid { get; set; }
        public int subjectid { get; set; }
        public Nullable<int> textbookid { get; set; }
        public string youtubelink { get; set; }
        public string publicdetail { get; set; }
        public Nullable<bool> isprivate { get; set; }
        public string privatedetail { get; set; }
        public Nullable<int> schoolid { get; set; }
        public bool isactive { get; set; }
        public int createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
    
        public virtual classlevel classlevel { get; set; }
        public virtual subject subject { get; set; }
        public virtual teacher teacher { get; set; }
        public virtual teacher teacher1 { get; set; }
        public virtual textbook textbook { get; set; }
    }
}
